FROM python:3.8.2

WORKDIR /usr/src
COPY Puertos/Generator /usr/src/Puertos/Generator
COPY Puertos/baseDatos /usr/src/Puertos/baseDatos
COPY Nucleo/Clases /usr/src/Nucleo/Clases
COPY Interfaces /usr/src/Interfaces
RUN pip install --no-cache-dir -r Puertos/Generator/Requiriments.txt

EXPOSE 27017

CMD ["python3","./Puertos/Generator/Executer.py"]